package com.ZZU.jQuery.setting.mapper;

import com.ZZU.jQuery.setting.pojo.User;
import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_users
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_users
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_users
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_users
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_users
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    int updateByPrimaryKey(User record);


    /**
     * 根据用户名和密码来查询用户信息
     * @param map
     * @return
     */
    User selectUserByNameAndPassword(Map<String,Object> map);

    /**
     * 注册用户，通过用户名和用户密码
     * @param map
     * @return
     */
    int insertUserByMap(Map<String ,Object> map);
}