package com.ZZU.jQuery.setting.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_users.id
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_users.username
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_users.password
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_users.phone
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_users.email
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_users.create_time
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_users.edit_time
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    private String editTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_users.lock_state
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    private String lockState;

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_users.id
     *
     * @return the value of tbl_users.id
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */

    private String loginName;
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_users.id
     *
     * @param id the value for tbl_users.id
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_users.username
     *
     * @return the value of tbl_users.username
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_users.username
     *
     * @param username the value for tbl_users.username
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_users.password
     *
     * @return the value of tbl_users.password
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_users.password
     *
     * @param password the value for tbl_users.password
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_users.phone
     *
     * @return the value of tbl_users.phone
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_users.phone
     *
     * @param phone the value for tbl_users.phone
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_users.email
     *
     * @return the value of tbl_users.email
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_users.email
     *
     * @param email the value for tbl_users.email
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_users.create_time
     *
     * @return the value of tbl_users.create_time
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_users.create_time
     *
     * @param createTime the value for tbl_users.create_time
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_users.edit_time
     *
     * @return the value of tbl_users.edit_time
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public String getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_users.edit_time
     *
     * @param editTime the value for tbl_users.edit_time
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public void setEditTime(String editTime) {
        this.editTime = editTime == null ? null : editTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_users.lock_state
     *
     * @return the value of tbl_users.lock_state
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public String getLockState() {
        return lockState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_users.lock_state
     *
     * @param lockState the value for tbl_users.lock_state
     *
     * @mbggenerated Sun Nov 20 17:37:19 CST 2022
     */
    public void setLockState(String lockState) {
        this.lockState = lockState == null ? null : lockState.trim();
    }
}